name: voila-gallery-country-indicators
channels:
- conda-forge
dependencies:
- matplotlib-base
- pandas
- ipywidgets==7.7.2
- jupyterlab>=3.1
- voila>=0.2.11
- plotly==5.5.0
- scipy==1.7.3
- seaborn==0.11.2
- numpy==1.21.6
