name: voila-gallery-country-indicators
channels:
- conda-forge
dependencies:
- matplotlib==3.2.2
- matplotlib-venn==0.11.7
- andas==1.3.5
- pandas-datareader==0.9.0
- pandas-gbq==0.17.9
- pandas-profiling==1.4.1
- ipywidgets==7.7.2
- jupyterlab>=3.1
- voila>=0.2.11
- plotly==5.5.0
- scipy==1.7.3
- seaborn==0.11.2
- numpy==1.21.6
